<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;

class Pendaftaran extends Model
{
    protected $fillable = [
        "tgl_daftar",
        "tingkat",
        "asal_sekolah",
        "alamat_asal_sekolah",
        "no_registrasi",
        "jurusan_id",
        "nama_siswa",
        "jenis_kelamin",
        "nisn",
        "nis",
        "nik",
        "npsn",
        "tmpt_lahir_siswa",
        "tgl_lahir_siswa",
        "agama",
        "kebutuhan_khusus_siswa",
        "alamat_siswa",
        "dusun",
        "rt",
        "rw",
        "kelurahan",
        "kecamatan",
        "kodepos",
        "kota",
        "provinsi",
        "transport",
        "jenis_tinggal",
        "telp_rmh",
        "telp_hp",
        "email",
        "no_kks",
        "kps",
        "no_kps",
        "usul_kip",
        "layak_kip",
        "penerima_kip",
        "no_kip",
        "nama_kip",
        "menolak_kip",
        "nama_ayah",
        "tgl_lahir_ayah",
        "kebutuhan_khusus_ayah",
        "pekerjaan_ayah",
        "pendidikan_ayah",
        "penghasilan_ayah",
        "nama_ibu",
        "tgl_lahir_ibu",
        "kebutuhan_khusus_ibu",
        "pekerjaan_ibu",
        "pendidikan_ibu",
        "penghasilan_ibu",
        "nama_wali",
        "tgl_lahir_wali",
        "kebutuhan_khusus_wali",
        "pekerjaan_wali",
        "pendidikan_wali",
        "penghasilan_wali",
        "tb",
        "bb",
        "jarak_kesekolah",
        "jarak_kesekolah_lainnya",
        "waktu_kesekolah",
        "waktu_kesekolah_lainnya",
        "saudara_kandung",
        "uk_baju",
    ];

    public function jurusan()
    {
        return $this->belongsTo(Jurusan::class, "jurusan_id");
    }
}
